name = "kauntah"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[durable_objects.bindings]]
name = "COUNTER"
class_name = "CounterDO"

[[migrations]]
tag = "v1"
new_classes = ["CounterDO"]

[[kv_namespaces]]
binding = "IMAGE_CACHE"
id = "7a7833463cc246a481427f565026fcfc"

[[rules]]
type = "Data"
globs = ["assets/**/*.png"]
fallthrough = false

[[unsafe.bindings]]
name = "RATE_LIMITER"
type = "ratelimit"
namespace_id = "1"
simple = { limit = 30, period = 60 }
