import { readFileSync, writeFileSync } from 'node:fs';

const root = new URL('../', import.meta.url);
const digits = Array.from({ length: 10 }, (_, digit) =>
  readFileSync(new URL(`assets/rule34/${digit}.gif`, root)).toString('base64')
);
writeFileSync(new URL('src/assets/rule34.ts', root),
  '// Generated by scripts/embed-rule34.mjs. Do not edit manually.\n' +
  '// Source: journey-ad/Moe-Counter; see assets/rule34/README.md and LICENSE.\n' +
  'export const RULE34_B64: string[] = ' + JSON.stringify(digits, null, 2) + ';\n'
);
